In [17]:
import numpy as np

def generate_toeplitz(cols, final_index):
    # Calculate the number of rows based on the final index and number of columns
    rows = final_index - cols + 2
    
    # Initialize a matrix filled with zeros
    matrix = np.zeros((rows, cols))
    
    # Fill the matrix such that it becomes a Toeplitz matrix
    for i in range(rows):
        for j in range(cols):
            value = i + j
            matrix[i, j] = min(value, final_index)
                
    return matrix

n_snapshot = 10
time_scale_factor = 4
# Example usage
total_number = 2000 # Total number of time steps
cols = n_snapshot 
 # Number of columns
final_index = total_number//time_scale_factor  # Final index number
toeplitz_matrix = generate_toeplitz(cols, final_index)
print("Generated Toeplitz Matrix:")
print(toeplitz_matrix*10)
print(toeplitz_matrix.shape)


Generated Toeplitz Matrix:
[[   0.   10.   20. ...   70.   80.   90.]
 [  10.   20.   30. ...   80.   90.  100.]
 [  20.   30.   40. ...   90.  100.  110.]
 ...
 [4890. 4900. 4910. ... 4960. 4970. 4980.]
 [4900. 4910. 4920. ... 4970. 4980. 4990.]
 [4910. 4920. 4930. ... 4980. 4990. 5000.]]
(492, 10)
